### ISSUE TITLE
Python 3.x: make test fails with undefined symbol: PyCObject_FromVoidPtr

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/python-gpsdshm#8]
```
Traceback (most recent call last):
  File "/python-gpsdshm/.tox/py33/lib/python3.3/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/imp.py", line 180, in load_module
    return load_source(name, filename, file)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/imp.py", line 119, in load_source
    _LoadSourceCompatibility(name, pathname, file).load_module(name)
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/python-gpsdshm/tests/test_gpsdshm.py", line 25, in <module>
    import gpsdshm
  File "/python-gpsdshm/gpsdshm/__init__.py", line 7, in <module>
    import gpsdshm.shm
  File "/python-gpsdshm/gpsdshm/shm.py", line 25, in <module>
    _shm = swig_import_helper()
  File "/python-gpsdshm/gpsdshm/shm.py", line 21, in swig_import_helper
    _mod = imp.load_module('_shm', fp, pathname, description)
  File "/python-gpsdshm/.tox/py33/lib/python3.3/imp.py", line 188, in load_module
    return load_dynamic(name, filename, file)
ImportError: /python-gpsdshm/gpsdshm/_shm.cpython-33m.so: undefined symbol: PyCObject_FromVoidPtr
```

**Comment by mjuenema** [comment]
See answer in http://stackoverflow.com/questions/28585977/cant-import-module-created-using-swig

```
rpm -qi swig
Name        : swig                         Relocations: (not relocatable)
Version     : 1.3.40                            Vendor: CentOS
```

**Comment by mjuenema** [comment]
Installed newer version of swig.
